# host_vars/pr001.yml
---
rhbase_firewall_allow_services:
  - ssh
  - dhcp

dhcp_global_max_lease_time: 43200

dhcp_global_subnet_mask: 255.255.0.0

dhcp_global_routers: 172.16.255.254

dhcp_global_domain_name: 'avalon.lan'

dhcp_global_domain_name_servers: 172.16.255.254

dhcp_subnets:

 - ip: 172.16.0.0
   netmask: 255.255.0.0
   domain_name_servers:
     - 172.16.255.254
   range_begin: 172.16.192.1
   range_end: 172.16.255.253
   default_lease_time: 43200

dhcp_hosts:
     - name: robin
       mac: '08:00:27:82:77:2A'
       ip: 172.16.128.10
     - name: WAN
       mac: '08:00:27:B1:24:DE'
       ip: 10.0.2.15
