---
rhbase_firewall_allow_services:
  - dhcp

dhcp_subnets:
  - ip: 172.16.0.0
    netmask: 255.255.0.0
    range_begin: 172.16.100.0
    range_end: 172.16.199.255
    routers: 192.0.2.254

dhcp_global_domain_name_servers:
  - 192.0.2.10
  - 192.0.2.11
