---
rhbase_firewall_allow_services:
  - http
  - https
  - dhcp

dhcp_max_lease_time: 43200
dhcp_global_subnet_mask: 255.255.0.0
dhcp_global_broadcast_address: 172.16.255.255
dhcp_global_domain_name: avalon.lan
dhcp_global_domain_name_servers:
  - 192.0.2.10
  - 192.0.2.11
dhcp_global_bootp: allow
dhcp_global_booting: allow

dhcp_global_classes:
  - name: vbox
    match: 'match if binary-to-ascii(16,8,":",substring(hardware, 1, 3)) = "8:0:27"'

dhcp_subnets:
  - ip: 172.16.0.0
    netmask: 255.255.0.0
    domain_name_servers:
      - 192.0.2.10
      - 192.0.2.11
    range_begin: 172.16.192.1
    range_end: 172.16.255.253
    routers: 172.16.255.254
    hosts:
      - name: reservering
        mac: 08:00:27:88:4A:5E
        ip: 172.16.128.1
