---
rhbase_firewall_allow_services:
  - samba
  - ftp
  - tftp
  - tftp-client
  - ssh

samba_workgroup: AVALON
samba_server_string: 'Welcome to the AVALON samba server!'
samba_load_printers: false
samba_load_homes: true
samba_create_varwww_symlinks: true
samba_log: /var/log/samba.log
samba_log_size: 60000
samba_netbios_name: FILES

rhbase_user_groups:
  - public
  - it
  - sales
  - technical
  - management

rhbase_users:
  - name: robin
    comment: 'Robin Roelandt'
    shell: /bin/bash
    password: '$6$egVvbvv90VbJfp9r$Ia.Uvw1l8qWcQBdUMPfXsEkhr1OHjvdukQhlZMYf1wkW9LJ5tk3uf8r2ko8jiUrJo1Zb7YiGIG8bDj2bpQEzM.'
    groups:
       - wheel
       - users
       - public
       - it
  - name: stevenh
    comment: 'Steven Hermans, CEO'
    password: '$6$L5oqw6iqXdSdr3Rq$vTgND.PBtiz5rsmOnnIYua5O1BtHH6N/JNrUi.3qdau9scLl/Ex.d2T8Jh50O0Gry0Fuut556a1cSL6ddqEs8/'
    groups:
      - public
      - management
  - name: stevenv
    comment: 'Steven van Daele, software engineer'
    password: '$6$O8UFipeH1DEPeN/x$Ua4LiQ9FjI2nkHqoavp1D3Wo4HjtrpyVGzUb2Hp7RGXuVjHBadwgpAXMZ.a0YDzvRoZD5myFBUavpQQo4bWA3.'
    groups:
      - public
      - technical
  - name: leend
    comment: 'Leen De Meester, software engineer'
    password: '$6$TM.MsRhcl.1N0hpq$MQ8jtellU2ejUv/WC8HJ1gqhnRezVG2EQQPSLKR8DONUdYfcUQinieaCpNAKYUu42OUq5ZXfaBQaBSU7c0irN/'
    groups:
      - public
      - technical
  - name: svena
    comment: 'Sven Aerens, Acount manager'
    password: '$6$.1kgQ0nvUnfCA3xn$JbgFXeLL5DL8WEaDEXuxI34rtNNDMXxvWvafq3MHd2XPRAx0xjSOKwG5dIxIJIQZ9Tq12S7homRQyRClPxMpC0'
    groups:
      - public
      - sales
  - name: nehirb
    comment: 'Behir Başar, System engineer'
    shell: /bin/bash
    password: '$6$TTygAOxA8TEElhvT$yRpHMOTwcY/tFEO30raT8To5JikIu3R7hchw6FT5kbzmDTLg6Z3/R8zywzbbVZx.7oOlYIIqlLaep5Eky60OP1'
    groups:
      - public
      - it
  - name: alexanderd
    comment: 'Alexander De Coninck, software engineer'
    password: '$6$gjAmhvf8z3xFiJTA$oUSZdQc7HhOcQyFnhlF9r3a28HKwP2w7nJiDNxIhoZ16a5dyr.ZbGAlF556lpiV5uviH5awmPqUTqECSFTym01'
    groups:
      - public
      - technical
  - name: krisv
    comment: 'Kris Vanhaverbeke, CFO'
    password: '$6$x8Rm4WtM75/EGQtt$UekWlqYpmIGHKnva2hZ1TJLWsFhMVf2RI45/wB.21B9szyYs4wYzT54Q2hOKs8dt15EdY5wECNCpLvusbMtH4/'
    groups:
      - public
      - management
  - name: benoitp
    comment: 'Benoit Pluquet, account manager'
    password: '$6$qJvJufLLePzoC7OC$En8Pjia2xnaZg3xaUjPzQx8YhpFPyk9CBSi1Ok4hxvbczMnloo6mAqqq13CPgcRjIrFmKyjFAAP/96xAFJpmf1'
    groups:
      - public
      - sales
  - name: anc
    comment: 'An Coppens, Graphical designer'
    password: '$6$gJAvx0eMR2NBTicR$URElJjGXMz3QfhhlqoRruOo8xCj6BnLa0NI14htGzX3eOUDh12nCLmAz0bJnNMUsC/SGabNSWhsLJpKJjRof61'
    groups:
      - public
      - technical
  - name: elenaa
    comment: 'Elena Andreev, Office Manager'
    password: '$6$worHktNyEO3m1j8/$lVHWLzyHFx6SycgYTYJSzTU6eQylsrrvi4wbsmJjAEmhxMwtmHJS8Xxgdqw92LklFruBJEOB082gR/F7epoe6/'
    groups:
      - public
      - management
  - name: evyt
    comment: 'Evy Tilleman, Technical Writer'
    password: '$6$XdNa78qW.aOYy7Bs$jQEadZiZ/r2rmkmdBGvRQdda.6jJg0gM9uuLdspiR3VOTZULgGZxujt2Ex/09hQP21ez.5My0Q1VCrYipxomp.'
    groups:
      - public
      - technical
  - name: christophev
    comment: 'Christophe Van der Meersche, System Administrator'
    shell: /bin/bash
    password: '$6$iktO6r9JgRL03o42$p2CYw2OfDNmyfbSMnIzblkOhstP0lV7IcNvVRmgjKAJ1SoN3RW2.FALilWW0T/6K7weZU22g7lhn0udjgx4zC/'
    groups:
      - public
      - it
  - name: stefaanv
    comment: 'Stefaan Vernimmen, Support Specialist'
    password: '$6$xwoOr209NIwBNue0$pIq0My6eFZB95.orEvMw5HWPh1aV0Z.12TmYUYoH1f1pqO9qWHF1HsXWp8pqvpleZB9r4uVZe1JcHp/eNXpZW1'
    groups:
      - public
      - technical

samba_users:
  - name: robin
    password: robin
  - name: stevenh
    password: stevenh
  - name: stevenv
    password: stevenv
  - name: leend
    password: leend
  - name: svena
    password: svena
  - name: nehirb
    password: nehirb
  - name: alexanderd
    password: alexanderd
  - name: krisv
    password: krisv
  - name: benoitp
    password: benoitp
  - name: anc
    password: anc
  - name: elenaa
    password: elenaa
  - name: evyt
    password: evyt
  - name: christophev
    password: christophev
  - name: stefaanv
    password: stefaanv

samba_shares:
  - name: public
    comment: 'public share'
    group: public
    write_list: +public

  - name: management
    comment: 'management share'
    group: management
    valid_users: +management
    write_list: +management
    directory_mode: '0770'

  - name: technical
    comment: 'technical share'
    group: technical
    public: yes
    write_list: +technical

  - name: sales
    comment: 'sales share'
    group: sales
    valid_users: +sales, +management
    write_list: +sales
    directory_mode: '0770'

  - name: it
    comment: 'it share'
    group: it
    valid_users: +it, +management
    write_list: +it
    directory_mode: '0770'

vsftpd_local_root: /srv/shares/
vsftpd_anonymous_enable: false
vsftpd_local_enable: true
