rhbase_firewall_allow_services:
  - dns

bind_zone_name: 'avalon.lan'

bind_zone_master_server_ip: 192.0.2.10

bind_zone_networks:
    - '192.0.2'
    - '172.16'
    - '10'

bind_zone_name_servers:
  - pu001
  - pu002
  - pu003
  - pu004
  - pr001
  - pr002
  - pr010
  - pr011

bind_allow_query:
  - any

bind_listen_ipv4:
  - any
