# host_vars/pu004.yml
---

rhbase_firewall_allow_services:
  - http
  - https

httpd_scripting: 'php'

mariadb_databases:
  - db

mariadb_users:
  - name: wp_user
    password: fogMeHud8
    priv: '*.*:ALL,GRANT'

mariadb_root_password: fogMeHud8

wordpress_user: wp_user
wordpress_password: CorkIgWac
