# host_vars/pu004.yml
---

rhbase_firewall_allow_services:
  - http
  - https

httpd_scripting: 'php'

mariadb_users:
  - name: wp_user
    password: fogMeHud8
    priv: wp_db.*:ALL

mariadb_root_password: fogMeHud8

wordpress_database: wp_db
wordpress_user: wp_user
wordpress_password: CorkIgWac
wordpress_home_url: http://192.0.2.50/wordpress/
