# host_vars/pu004.yml
---

rhbase_firewall_allow_services:
  - http
  - https

httpd_scripting: 'php'

mariadb_databases:
  - name: wordpress

mariadb_users:
  - name: robin
    password: VbfCmg2h9cuM8W77
    priv: wordpress.*:ALL,GRANT
    state: present

mariadb_root_password: VbfCmg2h9cuM8W77

wordpress_database: wordpress
wordpress_user: robin
wordpress_password: VbfCmg2h9cuM8W77

SSLCertificateFile: /etc/pki/tls/certs/ca.crt
SSLCertificateKeyFile: /etc/pki/tls/private/ca.key
