# site.yml
---
- hosts: pu001
  become: true
  roles:
    - bertvv.rh-base
    - bertvv.bind

- hosts: pu002
  become: true
  roles:
    - bertvv.rh-base
    - bertvv.bind

- hosts: pu004
  become: true
  roles:
    - bertvv.rh-base
    - bertvv.mariadb
    - bertvv.httpd
    - bertvv.wordpress
  pre_tasks:
  - copy: src=files/ca.crt dest=/etc/pki/tls/certs
  - copy: src=files/ca.key dest=/etc/pki/tls/private/ca.key

- hosts: pr011
  become: true
  roles:
    - bertvv.rh-base
    - bertvv.samba
    - bertvv.vsftpd
  post_tasks:
    - acl:
        path: /srv/shares/technical/
        default: yes
        entity: public
        etype: group
        permissions: r
        state: present
    - acl:
        path: /srv/shares/it/
        default: yes
        entity: management
        etype: group
        permissions: r
        state: present
    - acl:
        path: /srv/shares/sales/
        default: yes
        entity: management
        etype: group
        permissions: r
        state: present

- hosts: pr001
  become: true
  roles:
    - bertvv.rh-base
    - bertvv.dhcp
