# site.yml
---
- hosts: pu001
  become: true
  roles:
    - bertvv.rh-base
    - bertvv.bind

- hosts: pu004
  become: true
  roles:
    - bertvv.rh-base
    - bertvv.mariadb
    - bertvv.httpd
    - bertvv.wordpress
  tasks:
  - copy: src=/vagrant/Certificaat/ca.crt dest=/etc/pki/tls/certs
  - copy: src=/vagrant/Certificaat/ca.key dest=/etc/pki/tls/private/ca.key
  - copy: src=/vagrant/Certificaat/ca.csr dest=/etc/pki/tls/private/ca.csr
